ALTER TABLE users
    ADD COLUMN IF NOT EXISTS age SMALLINT NULL AFTER name,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL AFTER age,
    ADD COLUMN IF NOT EXISTS ai_notes VARCHAR(255) NULL AFTER image_user,
    ADD COLUMN IF NOT EXISTS date_of_birth DATE NULL AFTER name,
    ADD COLUMN IF NOT EXISTS note VARCHAR(20) NULL AFTER ai_notes;
