ALTER TABLE users
    ADD COLUMN IF NOT EXISTS age SMALLINT NULL AFTER name,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL AFTER age,
    ADD COLUMN IF NOT EXISTS ai_notes VARCHAR(255) NULL AFTER image_user;
